# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - testing

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      server:
        # Docker Hub image
        image: ghcr.io/yuvraj9/key-value-store-main:latest
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 5000:5000

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: |
        pip install tox tox-gh-actions
        pip install -r requirements.txt
    # Runs a set of commands using the runners shell
    - name: Running test
      run: |
        tox
      env:
        # The hostname used to communicate with the server container
        URL: http://server:5000